In [1]:
import numpy as np

In [2]:
lst=[1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


In [4]:
a=np.array([(1,2,3,4)])
b=np.array([(1,2,3,4),
      (5,6,7,8)])
c=np.array([(1,2,3,4),
      (5,6,7,8),
      (9,10,11,12)])

print(a)
print(b)
print(c)

[[1 2 3 4]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
print(a.size)
print(b.size)
print(c.size)

4
8
12


In [7]:
print(a.shape)
print(b.shape)
print(c.shape)

(1, 4)
(2, 4)
(3, 4)


In [9]:
print(c.transpose())

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
